Run turret indexing in disabled
thedropbears/pycubehammer pull request #20
Opened 2023-04-04 05:33 UTC by OliverW10

Runs the turret indexing detection in disabled to allow manually moving the turret to its limit before matches, will still run the zeroing routine if it hasn't hit a limit yet when its enabled. To make moving it while disabled easier given it sets the motor to coast mode when disabled.

2023-04-04 06:19 UTC, james-ward requested changes
This will break the motion profiling. It has to be driven off the limit switch at a constant voltage - that is why it was set up that way in the first place

2023-04-04 06:48 UTC, OliverW10 commented
I don't know if the reset would have fixed it, I changed it to have the old behavior

2023-04-04 07:59 UTC, auscompgeek commented on components/turret.py
> +        return self.index_found
Instead of adding a feedback method for this, how about making index_found a tunable?

2023-04-04 22:14 UTC, LucienMorey commented
@OliverW10 I have now pushed the changes from last night during testing.

There are two competing problems that we need to deal with, both seemingly related to the profiled pid controller.


1. With your code as it was, The turret would rush back to one of the limits before returning to its true setpoint. We thought the fix to this would be resetting the rotation controller on enable, but that didn't work. Once I removed the reset call from the switch engagement method, it behaved as expected, almost like you could only reset once during disabled or something. Strangely enough, there was enough time in this process to go through multiple control cycles, and in that time, it just ignored its true setpoint.
2. Fixing problem 1 brought back problem 2. We must reset the rotation controller after it finds the index so it doesn't just send it back to the current setpoint once it comes off the switch. We hypothesise that the profiled pid controller will keep ticking while the turret is in contact with the limit switch, and while in contact with the switch, we will keep resetting the angle so the controller thinks its not moving at all. When the switch finally deactivates, the turret is behind in the scheduled profile so it has to catch up.

@james-ward @auscompgeek I feel like I have not done a very good job at capturing all of the elements of this issue. If you can see points that I have clearly missed, I would appreciate you adding more information.

2023-04-11 23:05 UTC, james-ward approved these changes
You are an epic winner!

2023-04-12 00:13 UTC, merged