Keep tilt clear of intake when moving
thedropbears/pycubehammer pull request #44
Opened 2023-05-14 07:26 UTC by auscompgeek

2023-05-14 07:27 UTC, auscompgeek commented on controllers/shooter.py
> +        self.turret_component.set_angle(bs.tilt_angle)
This state shouldn't move the turret before moving the tilt, right?
```suggestion
```

2023-05-14 23:18 UTC, james-ward requested changes

2023-05-14 23:18 UTC, james-ward commented on controllers/shooter.py
> +        if self.turret_component.at_angle():
I think we still want to make sure the tilt component is in the correct position before we deploy the intake.
```suggestion
        if self.turret_component.at_angle() and self.tilt_component.at_angle():
```

2023-05-15 11:06 UTC, james-ward approved these changes

2023-05-15 11:08 UTC, merged